from ui.popUp.popup import Error


class AbstractTableModel():

    def load(self, file=None): ...

    def save(self): ...

    def find(self, txt): ...

    def filter(self, parm): ...

    def change(self, row, col, value): ...

    def delete(self, index): ...

    def add(self, data): ...

    def split(self, arr): ...

    def merge(self, arr): ...

    def toolbar(self): ...

    def info(self, action_type, err_code, des=""):
        parm = action_type.value[1]
        Error(parm["title"], parm["msg"], err_code, des)

    def write_log(self, action_type, parm): ...
